[build]
  publish = "public" # Confirme que sua pasta de arquivos estáticos é realmente 'public'
  command = "envsubst < public/register.html > public/register_temp.html && mv public/register_temp.html public/register.html"

[build.environment]
  API_ENDPOINT = "https://back-end-site-bytebros-nuot.onrender.com/api/" # SUA URL DO RENDER, TERMINANDO COM /api/

[build.processing.html]
  enable = true
